// Regenerates src/community-domains.ts from the community-maintained
// disposable-email-domains blocklist (CC0): https://github.com/disposable-email-domains/disposable-email-domains
// Usage: npm run update-domains
import { writeFileSync } from "node:fs";

const SOURCE_URL =
  "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf";

// Never block these, even if they show up upstream
const NEVER_BLOCK = new Set([
  "gmail.com", "googlemail.com", "outlook.com", "hotmail.com", "live.com", "msn.com",
  "yahoo.com", "icloud.com", "me.com", "mac.com", "aol.com", "protonmail.com", "proton.me",
  "gmx.com", "gmx.de", "gmx.net", "web.de", "mail.ru", "yandex.com", "yandex.ru",
  "zoho.com", "fastmail.com", "tutanota.com", "tuta.io", "hey.com", "qq.com", "163.com",
]);

const res = await fetch(SOURCE_URL);
if (!res.ok) throw new Error(`Failed to fetch blocklist: ${res.status}`);

const domains = [
  ...new Set(
    (await res.text())
      .split("\n")
      .map((l) => l.trim().toLowerCase())
      .filter((l) => /^[a-z0-9.-]+\.[a-z0-9-]+$/.test(l) && !NEVER_BLOCK.has(l))
  ),
].sort();

const out = `// AUTO-GENERATED by scripts/update-domains.js — do not edit by hand.
// Source: https://github.com/disposable-email-domains/disposable-email-domains (CC0)
// Last updated: ${new Date().toISOString().slice(0, 10)} (${domains.length} domains)
const COMMUNITY_DOMAINS: readonly string[] = ${JSON.stringify(domains)};

export default COMMUNITY_DOMAINS;
`;

writeFileSync(new URL("../src/community-domains.ts", import.meta.url), out);
console.log(`Wrote ${domains.length} domains to src/community-domains.ts`);
