// Regenerates src/community-domains.ts from several community-maintained
// disposable-email blocklists. A domain is kept only if it appears in at
// least MIN_SOURCES of them, which filters out one-off/novelty entries
// while keeping anything multiple independent maintainers agree on.
// Usage: npm run update-domains
import { writeFileSync } from "node:fs";

const SOURCES = [
  // CC0 — https://github.com/disposable-email-domains/disposable-email-domains
  "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf",
  // MIT — https://github.com/disposable/disposable-email-domains
  "https://disposable.github.io/disposable-email-domains/domains.txt",
  // MIT — https://github.com/FGRibreau/mailchecker
  "https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.txt",
  // BSD-3-Clause — https://github.com/7c/fakefilter
  "https://raw.githubusercontent.com/7c/fakefilter/main/txt/data.txt",
];

// A domain must show up in at least this many of the sources above to be
// included, so a single source's quirks/novelty entries don't bloat the list.
const MIN_SOURCES = 2;

// Never block these, even if they show up upstream
const NEVER_BLOCK = new Set([
  "gmail.com", "googlemail.com", "outlook.com", "hotmail.com", "live.com", "msn.com",
  "yahoo.com", "icloud.com", "me.com", "mac.com", "aol.com", "protonmail.com", "proton.me",
  "gmx.com", "gmx.de", "gmx.net", "web.de", "mail.ru", "yandex.com", "yandex.ru",
  "zoho.com", "fastmail.com", "tutanota.com", "tuta.io", "hey.com", "qq.com", "163.com",
]);

const DOMAIN_RE = /^[a-z0-9.-]+\.[a-z0-9-]+$/;

const counts = new Map();

for (const url of SOURCES) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  const text = await res.text();

  const seenInThisSource = new Set(
    text
      .split("\n")
      .map((l) => l.trim().toLowerCase())
      .filter((l) => l && !l.startsWith("#") && DOMAIN_RE.test(l) && !NEVER_BLOCK.has(l))
  );

  for (const domain of seenInThisSource) {
    counts.set(domain, (counts.get(domain) ?? 0) + 1);
  }
}

const domains = [...counts.entries()]
  .filter(([, count]) => count >= MIN_SOURCES)
  .map(([domain]) => domain)
  .sort();

const out = `// AUTO-GENERATED by scripts/update-domains.js — do not edit by hand.
// Sources (domain kept if it appears in >= ${MIN_SOURCES} of them):
//  - https://github.com/disposable-email-domains/disposable-email-domains (CC0)
//  - https://github.com/disposable/disposable-email-domains (MIT)
//  - https://github.com/FGRibreau/mailchecker (MIT)
//  - https://github.com/7c/fakefilter (BSD-3-Clause)
// Last updated: ${new Date().toISOString().slice(0, 10)} (${domains.length} domains)
const COMMUNITY_DOMAINS: readonly string[] = ${JSON.stringify(domains)};

export default COMMUNITY_DOMAINS;
`;

writeFileSync(new URL("../src/community-domains.ts", import.meta.url), out);
console.log(`Wrote ${domains.length} domains to src/community-domains.ts`);
